In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Customer_Data.csv")
df.head()

Mounted at /content/drive

,Customer_ID,Name,Age,Gender,Marital_Status,Employment_Type,Monthly_Income,Loan_Amount_Requested,Credit_Score,Existing_EMI,...,Bank_Statement_Verified,Voice_Verified,Document_Verified,Debt_to_Income_Ratio,Total_Liabilities,Past_Defaults,Region,Loan_Purpose,Eligibility_Score,Loan_Approved
0,C001,Rohan Singh,21,M,Married,Business,48122,701743,896,26653,...,Yes,No,No,0.55,247952,2,Hyderabad,Home,0.33,0
1,C002,Tanya Kumar,36,F,Married,Job,90494,864822,440,3588,...,Yes,No,Yes,0.04,393160,0,Delhi,Personal,0.65,0
2,C003,Sneha Singh,46,F,Single,Business,127446,804413,608,5095,...,Yes,No,Yes,0.04,287727,2,Chennai,Education,0.47,0
3,C004,Tanya Singh,57,M,Single,Business,124572,591019,563,27927,...,No,Yes,Yes,0.22,149597,0,Bangalore,Education,0.39,0
4,C005,Amit Patel,53,F,Married,Business,59344,992266,437,28827,...,No,No,No,0.49,329539,2,Mumbai,Home,0.95,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Customer_ID              100 non-null    object
 1   Name                     100 non-null    object
 2   Age                      100 non-null    int64
 3   Gender                   100 non-null    object
 4   Marital_Status           100 non-null    object
 5   Employment_Type          100 non-null    object
 6   Monthly_Income           100 non-null    int64
 7   Loan_Amount_Requested    100 non-null    int64
 8   Credit_Score             100 non-null    int64
 9   Existing_EMI             100 non-null    int64
 10  Loan_Tenure_Years        100 non-null    int64
 11  Dependents               100 non-null    int64
 12  Bank_Statement_Verified  100 non-null    object
 13  Voice_Verified           100 non-null    object
 14  Document_Verified        100 non-null    object
 15  Debt_to_Income_Ratio     100 non-null    float64
 16  Total_Liabilities        100 non-null    int64
 17  Past_Defaults            100 non-null    int64
 18  Region                   100 non-null    object
 19  Loan_Purpose             100 non-null    object
 20  Eligibility_Score        100 non-null    float64
 21  Loan_Approved            100 non-null    int64
dtypes: float64(2), int64(10), object(10)
memory usage: 17.3+ KB

In [ ]:
df.describe()

,Age,Monthly_Income,Loan_Amount_Requested,Credit_Score,Existing_EMI,Loan_Tenure_Years,Dependents,Debt_to_Income_Ratio,Total_Liabilities,Past_Defaults,Eligibility_Score,Loan_Approved
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,41.590000,88198.070000,570161.400000,591.560000,16101.590000,4.780000,1.820000,0.221400,283629.460000,1.380000,0.616200,0.220000
std,11.427501,31873.792379,253835.432096,172.733772,8190.944574,2.865962,1.373486,0.169342,138097.797784,1.042336,0.195845,0.416333
min,21.000000,30945.000000,104228.000000,303.000000,2035.000000,1.000000,0.000000,0.020000,53214.000000,0.000000,0.300000,0.000000
25%,33.750000,63085.000000,373830.250000,439.750000,9789.750000,2.000000,1.000000,0.100000,148964.000000,1.000000,0.450000,0.000000
50%,42.000000,86372.000000,590370.000000,585.000000,15260.500000,4.000000,2.000000,0.175000,288438.500000,1.000000,0.590000,0.000000
75%,50.250000,111637.000000,777448.250000,726.500000,23867.500000,7.000000,3.000000,0.282500,408954.250000,2.000000,0.790000,0.000000
max,60.000000,149035.000000,996618.000000,898.000000,29773.000000,10.000000,4.000000,0.750000,496098.000000,3.000000,0.950000,1.000000

In [ ]:
df.shape

(100, 22)

In [ ]:
df.isnull().sum()

Customer_ID                0
Name                       0
Age                        0
Gender                     0
Marital_Status             0
Employment_Type            0
Monthly_Income             0
Loan_Amount_Requested      0
Credit_Score               0
Existing_EMI               0
Loan_Tenure_Years          0
Dependents                 0
Bank_Statement_Verified    0
Voice_Verified             0
Document_Verified          0
Debt_to_Income_Ratio       0
Total_Liabilities          0
Past_Defaults              0
Region                     0
Loan_Purpose               0
Eligibility_Score          0
Loan_Approved              0
dtype: int64

In [ ]:
df.columns

Index(['Customer_ID', 'Name', 'Age', 'Gender', 'Marital_Status',
       'Employment_Type', 'Monthly_Income', 'Loan_Amount_Requested',
       'Credit_Score', 'Existing_EMI', 'Loan_Tenure_Years', 'Dependents',
       'Bank_Statement_Verified', 'Voice_Verified', 'Document_Verified',
       'Debt_to_Income_Ratio', 'Total_Liabilities', 'Past_Defaults', 'Region',
       'Loan_Purpose', 'Eligibility_Score', 'Loan_Approved'],
      dtype='object')

In [ ]:
for col in df.columns:
  print(col,"::",df[col].dtypes,"unique count: ", df[col].nunique())

Customer_ID :: object unique count:  100
Name :: object unique count:  37
Age :: int64 unique count:  36
Gender :: object unique count:  2
Marital_Status :: object unique count:  2
Employment_Type :: object unique count:  3
Monthly_Income :: int64 unique count:  100
Loan_Amount_Requested :: int64 unique count:  100
Credit_Score :: int64 unique count:  92
Existing_EMI :: int64 unique count:  100
Loan_Tenure_Years :: int64 unique count:  10
Dependents :: int64 unique count:  5
Bank_Statement_Verified :: object unique count:  2
Voice_Verified :: object unique count:  2
Document_Verified :: object unique count:  2
Debt_to_Income_Ratio :: float64 unique count:  45
Total_Liabilities :: int64 unique count:  100
Past_Defaults :: int64 unique count:  4
Region :: object unique count:  6
Loan_Purpose :: object unique count:  5
Eligibility_Score :: float64 unique count:  52
Loan_Approved :: int64 unique count:  2

In [ ]:
for col in df.columns:
    print(f"{col:25} | dtype: {str(df[col].dtypes):10} | unique: {df[col].nunique():5} | missing: {df[col].isna().sum():5}")

Customer_ID               | dtype: object     | unique:   100 | missing:     0
Name                      | dtype: object     | unique:    37 | missing:     0
Age                       | dtype: int64      | unique:    36 | missing:     0
Gender                    | dtype: object     | unique:     2 | missing:     0
Marital_Status            | dtype: object     | unique:     2 | missing:     0
Employment_Type           | dtype: object     | unique:     3 | missing:     0
Monthly_Income            | dtype: int64      | unique:   100 | missing:     0
Loan_Amount_Requested     | dtype: int64      | unique:   100 | missing:     0
Credit_Score              | dtype: int64      | unique:    92 | missing:     0
Existing_EMI              | dtype: int64      | unique:   100 | missing:     0
Loan_Tenure_Years         | dtype: int64      | unique:    10 | missing:     0
Dependents                | dtype: int64      | unique:     5 | missing:     0
Bank_Statement_Verified   | dtype: object     | unique:     2 | missing:     0
Voice_Verified            | dtype: object     | unique:     2 | missing:     0
Document_Verified         | dtype: object     | unique:     2 | missing:     0
Debt_to_Income_Ratio      | dtype: float64    | unique:    45 | missing:     0
Total_Liabilities         | dtype: int64      | unique:   100 | missing:     0
Past_Defaults             | dtype: int64      | unique:     4 | missing:     0
Region                    | dtype: object     | unique:     6 | missing:     0
Loan_Purpose              | dtype: object     | unique:     5 | missing:     0
Eligibility_Score         | dtype: float64    | unique:    52 | missing:     0
Loan_Approved             | dtype: int64      | unique:     2 | missing:     0

In [ ]:
# Columns with mixed types or stored as object but look numeric
for col in df.select_dtypes(include='object'):
    try:
        df[col].astype(float)
        print(f"⚠️ Column '{col}' seems numeric but stored as object")
    except:
        pass

In [ ]:
numeric_col = df.select_dtypes(include = ['int64','float64']).columns
print("Numeric columns: ",list[numeric_col])

Numeric columns:  list[Index(['Age', 'Monthly_Income', 'Loan_Amount_Requested', 'Credit_Score',
       'Existing_EMI', 'Loan_Tenure_Years', 'Dependents',
       'Debt_to_Income_Ratio', 'Total_Liabilities', 'Past_Defaults',
       'Eligibility_Score', 'Loan_Approved'],
      dtype='object')]

In [ ]:
for col in numeric_col:
    unique_values = df[col].unique()
    invalid_values = [v for v in unique_values if isinstance(v, str)]
    if invalid_values:
        print(f"⚠️ Column '{col}' has non-numeric values: {invalid_values[:10]}")
    else:
        print(f"✅ Column '{col}' is clean (all numeric)")

✅ Column 'Age' is clean (all numeric)
✅ Column 'Monthly_Income' is clean (all numeric)
✅ Column 'Loan_Amount_Requested' is clean (all numeric)
✅ Column 'Credit_Score' is clean (all numeric)
✅ Column 'Existing_EMI' is clean (all numeric)
✅ Column 'Loan_Tenure_Years' is clean (all numeric)
✅ Column 'Dependents' is clean (all numeric)
✅ Column 'Debt_to_Income_Ratio' is clean (all numeric)
✅ Column 'Total_Liabilities' is clean (all numeric)
✅ Column 'Past_Defaults' is clean (all numeric)
✅ Column 'Eligibility_Score' is clean (all numeric)
✅ Column 'Loan_Approved' is clean (all numeric)